os: osx
osx_image: xcode10.1
branches:
  only:
    - master
cache: bundler
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=WorkSchedule.xcworkspace
install:
  - bundle install
  - pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - fastlane test